spring.application.name=HostelManagment

spring.datasource.url=jdbc:postgresql://localhost:5432/hostel_management
spring.datasource.username=postgres
spring.datasource.password=Admin@123

jwt.secret = fjb2387rbqjwhfb2873fqjhbf8723grfjhb387jhb3287grbqejhfb
jwt.expiration-ms= 30000000000000000

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# MongoDB Atlas connection URI
#spring.data.mongodb.uri=mongodb+srv://krushnasalbande_db_user:83HFEKcWth0IfgtV@cluster0.z4fjqwm.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri = mongodb://localhost:27017/hostel_management
server.port=8080
# Optional (recommended)
spring.data.mongodb.auto-index-creation=true



