spring.application.name=HostelManagment

# ===============================
# ACTIVE PROFILE (dev | prod)
# ===============================
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/hostel_management
spring.datasource.username=postgres
spring.datasource.password=Admin@123

jwt.secret = fjb2387rbqjwhfb2873fqjhbf8723grfjhb387jhb3287grbqejhfb
jwt.expiration-ms= 30000000000000000

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# SQL logging is controlled via logback-spring.xml (org.hibernate.SQL logger)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGGING
# ===============================
logging.file.name=./logs/hostel-management.log

# MongoDB Atlas connection URI
#spring.data.mongodb.uri=mongodb+srv://krushnasalbande_db_user:83HFEKcWth0IfgtV@cluster0.z4fjqwm.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri = mongodb://localhost:27017/hostel_management
# Optional (recommended)
spring.data.mongodb.auto-index-creation=true



